### PR TITLE
fixed issues with sidebar affecting matches.vue

### LINKED ISSUE #269: fix issues with teams page ui

### PR DESCRIPTION
**Pull request by PrestonSwigart**
thanks ryan

### CODE REVIEW

**Comment by PrestonSwigart** [comment]
dont merge

**Comment by Ryan-Bauroth** [comment]
hmm... not sure why the action is failing, but it seems like vueuse? There doesn't seem to be a bug in the code though?

**Comment by Ryan-Bauroth** [comment]
@PrestonSwigart @nataliemcwhorter  any ideas of what this could be

File: pages/dashboard.vue [hunk 1]
```diff
@@ -594,6 +594,7 @@ async function updateTeamData() {
           />
         </UCarousel>
       </UCard>
+      <div v-else></div>
```
Comment (Ryan-Bauroth) [inline pages/dashboard.vue:597]: why?

Comment (Ryan-Bauroth) [reply pages/dashboard.vue:597]: oh is this one of the errors you found @PrestonSwigart while trying to debug.

**Review by Ryan-Bauroth — APPROVED** [review]
looks good! at some point we might want to make the teams page more easily updatable, but totally works for now
